import { Inter } from "next/font/google";
import "./globals.css";
import Twetter from "./components/Twetter";
import ReduxProviders from "./GlobalRedux/storeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProviders>
          <Twetter />
          {children}
        </ReduxProviders>
      </body>
    </html>
  );
}
